pipeline:
  build:
    image: openjdk:8-jdk
    commands:
      - pwd
      - ls -al
      - java -version
  telegram:
    image: appleboy/drone-telegram
    token: 395253918:AAGItI8SnBltjA-niCdRIza2AD9Ocbkrbik
    to: 288567681
    format: markdown
    message: >
      {{#success build.status}}
        `{{build.number}}` successed at {{build.finished}}. Good job.
      {{/success}}
    when:
      status: [ success, failure ]
