pipeline:
  build:
    image: openjdk:8-jdk
    commands:
      - pwd
      - ls -al
      - java -version
  telegram:
    image: appleboy/drone-telegram
    format: markdown
    message: >
      {{#success build.status}}
        `{{build.number}}` successed at {{build.finished}}. Good job.
      {{/success}}
    when:
      status: [ success, failure ]
    secrets: [ telegram_token, telegram_to ]
